# Generated by Django 5.2 on 2025-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
